### ISSUE TITLE
No dependance with the Telemetry Dashboard please

### ISSUE THREAD

**Issue by simonaubertbd** [eapowertools/qs-extension-usage-dashboard#5]
Hello,

I'm not sure to understand why there is a dependance with the Telemetry Dashboard. I mean : I read the script, found where the TD data is used... but I think an independant extension usage dashboard would be better : easier to install, easier to maintain., easier to schedule, etc.. and the TD has some issues of its own.

Best regards,

Simon

**Comment by levi-turner** [comment]
@simonaubertbd : You're certainly welcome to develop a method to build out a metadata store of the visualizations inside of apps which can then be plugged into this app. The metadata will require Engine API calls to fetch the data so the degree of difficulty is high. But our team does not see the value in recreating the wheel for this use case. Minimally you only need the `TelemetryDashboard-1-Generate-Metadata` task to complete for this app to have what it needs.
