### ISSUE TITLE
The following error occurred: HTTP protocol error 400 (Bad Request):

### ISSUE THREAD

**Issue by Freighar** [eapowertools/qs-extension-usage-dashboard#8]
Hi!,

I get an error reloading the app, i think it has something to do with the url but i have not managed to do correct the issue.

FROM JSON (wrap on) "root" PK "__KEY_root"
WITH CONNECTION(
    URL "https://MyServrMachineName.domain/qrs/app/object/full?filter=objectType eq 'sheet'",
    QUERY "xrfkey" "abcdefg123456789",
    HTTPHEADER "X-Qlik-Xrfkey" "abcdefg123456789"
)

**Comment by levi-turner** [comment]
Is this with Qlik Sense Enterprise June 2020?

**Comment by Freighar** [comment]
Oh Yes.... this update is getting very troublesome. Actually i want to check the extension dashboard because a lot of them don't work on june 2020....

Thanks!

**Comment by levi-turner** [comment]
Gotcha. I am seeing the same issue on my June 2020 installation. I'll comment tomorrow with a work-around.

**Comment by levi-turner** [comment]
This copy should work.
[Extension Usage Dashboard - REST Connector Fix.zip](https://github.com/eapowertools/qs-extension-usage-dashboard/files/4820366/Extension.Usage.Dashboard.-.REST.Connector.Fix.zip)

**Comment by Freighar** [comment]
It Works! Great!.

Thanks a lot! and congratulations for the extension, is very useful.

**Comment by levi-turner** [comment]
Should be handled in the latest release in a more elegant manner: https://github.com/eapowertools/qs-extension-usage-dashboard/releases/tag/2.0.0
